source 'https://rubygems.org'
ruby '2.7.0'

gem 'rails', '5.2.3'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'therubyrhino'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'

# Grateful Dev Gems
gem 'js-routes'
gem 'eco'
gem 'gon'
gem 'gdshowsdb', :git => 'git://github.com/jefmsmit/gdshowsdb.git'
gem 'compass-rails'
gem 'bootstrap-sass'
