source 'https://rubygems.org'
ruby '2.1.2'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyrhino'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

# Grateful Dev Gems
gem 'js-routes'
gem 'eco'
gem 'gon'
gem 'gdshowsdb', :git => 'git://github.com/jefmsmit/gdshowsdb.git'
gem 'compass-rails'
gem 'bootstrap-sass'
